In [ ]:
# Assignment 3 Session 1

In [1]:
# Question 1.
# Write a function to compute 5/0 and use try/except to catch the exceptions. 3 Session 1

def div(n1,n2):
        try:
            print("In Try !!!   ")
            out= n1/n2               
        except ZeroDivisionError as e:   # Catching Zero Division Exception
            print("Inside Exception !!! " +str(e))
        else:                      # Printing calculated value if there are no exception
            print("Inside Else !!!  "+str(out))            
        finally:                   # Printing irrespective of exception occurred or not
            if(n2==0):
                print("Inside Finally !!! Try with different denominator")
            else:
                print("Inside Finally !!! Calculation Successful !!!")
                        
num1 = int(input("Enter Number 1 : "))
num2 = int(input("Enter Number 2 : "))
div(num1,num2)

Enter Number 1 : 5
Enter Number 2 : 0
In Try !!!   
Inside Exception !!! division by zero
Inside Finally !!! Try with different denominator


In [2]:
# Question 2
# Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
# Hint: Subject,Verb and Object should be declared in the program as shown below.
# subjects=["Americans ","Indians"]
# verbs=["play","watch"]
# objects=["Baseball","Cricket"]

subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

sentence=[(sub+" "+ver+" "+obj) for sub in subjects for ver in verbs for obj in objects]
for sent in sentence:
    print(sent)


Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [3]:
# Question 3
# The columns of the output matrix are powers of the input vector. 
# The order of the powers is determined by the increasing boolean argument. 
# Specifically, when increasing is False, the i-th output column is the input vector raised element-wise 
# to the power of N - i - 1. 
# Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.

import numpy as np

def myvander(x, N=None, increasing=False):
    if increasing==False:
        return (np.column_stack([x**(N-i-1) for i in range(N)]))
    else:
        return (np.column_stack([x**(i) for i in range(0,N)]))

x=np.array([1,2,3,5])
N=3
print("Decreasing")
print(myvander(x,N,False))
print("="*20)
print("Increasing")
print(myvander(x,N,True))


Decreasing
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]
Increasing
[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  5 25]]
